services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env 
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
    
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "127.0.0.1:80:80"
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

# BONUS: resume static website
  resume:
    build:
      context: ./requirements/bonus/resume
    image: resume
    container_name: resume
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - inception
    restart: always

# BONUS: adminer for database management
  adminer:
    build:
      context: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

# BONUS: Portainer for Docker management
  portainer:
    build:
      context: ./requirements/bonus/portainer
    image: portainer
    container_name: portainer
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    restart: always
    
volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind
  
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind

  portainer_data:
    name: portainer_data
    driver: local

networks:
  inception:
    name: inception
    driver: bridge
