services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env 
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/olean/data/mariadb # change olean to 42 login
      o: bind
  
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/olean/data/wordpress # change to your login
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
